server:
  dev: true
  port: 8080
  host: 

token:
  header: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  expiration: 30

file:
  avatar:
    rootStore: ./view/static/avatar
    rootUrl: /static/avatar

sqlite:
    path: sqlite3.db

redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 0
    useCluster: false
    clusterAddrs:
        - 172.21.0.3:7000
        - 172.21.0.4:7001
        - 172.21.0.2:7002

login:
  # 密码最大错误次数
  maxRetryCount: 5
  # 密码锁定时间（默认10分钟）
  lockTime: 10

openvpn:
  mgmtUrl: http://47.115.231.143:8988